global: &global
  adapter: postgresql
  username: dev
  password: 123
  min_messages: warning

development:
  database: lunch_bunch_development
  <<: *global

test: &test
  database: lunch_bunch_test
  pool: 10
  <<: *global

cucumber:
  <<: *test
